name: ml-apartment-rents
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - shap
    - jupyter
    - joblib
